name: DEPLOYMENT 

on:
  pull_request_review:
    branches: [main]


jobs:
  build:
    runs-on: [self-hosted, windows, x64]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: create delta-package
        run: |
          $pathsString = git diff origin/main origin/${{ github.head_ref }} --name-only force-app
          Write-Host $pathsString
          $pathArray = $pathsString.Split()

          mkdir delta-package

          $pathArray | ForEach{
              
              $splitedPath = $_.Split("/")
              $destination = "delta-package"+"/main/default/"+$splitedPath[3]+"/"+$splitedPath[4]
              if (!(Test-Path -path $destination)) {New-Item $destination -Type Directory}

              $toCopy = "force-app"+"/main/default/"+$splitedPath[3]+"/"+$splitedPath[4]
              WRITE-HOST $toCopy
              Copy-Item $toCopy/* -Destination $destination

          }
      - name: authorization
        run: |
          New-Item -Name "server.key" -ItemType File -Value "${{ secrets.JWTKEYFILE }}"
          sfdx force:auth:jwt:grant --setalias MyOrg --jwtkeyfile server.key --clientid ${{ secrets.CONSUMERKEY }} -u ${{ secrets.USR }}

      - name: deployment
        run: |
          sfdx force:source:deploy --sourcepath delta-package -u MyOrg
